export enum EventNames {
  OPEN_CONNECT_WALLET_MODAL = 'OPEN_CONNECT_WALLET_MODAL',
  WALLET_CONNECTED = 'WALLET_CONNECTED',
  WALLET_DISCONNECTED = 'WALLET_DISCONNECTED',
}

export type EventListeners = {};
