/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StorybookLazyImport = createFileRoute('/storybook')()
const EntepriseListLazyImport = createFileRoute('/enteprise-list')()
const EntepriseLazyImport = createFileRoute('/enteprise')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const CollectedCredsLazyImport = createFileRoute('/collected-creds')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StorybookLazyRoute = StorybookLazyImport.update({
  path: '/storybook',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/storybook.lazy').then((d) => d.Route))

const EntepriseListLazyRoute = EntepriseListLazyImport.update({
  path: '/enteprise-list',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/enteprise-list.lazy').then((d) => d.Route),
)

const EntepriseLazyRoute = EntepriseLazyImport.update({
  path: '/enteprise',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/enteprise.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const CollectedCredsLazyRoute = CollectedCredsLazyImport.update({
  path: '/collected-creds',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/collected-creds.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/collected-creds': {
      preLoaderRoute: typeof CollectedCredsLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/enteprise': {
      preLoaderRoute: typeof EntepriseLazyImport
      parentRoute: typeof rootRoute
    }
    '/enteprise-list': {
      preLoaderRoute: typeof EntepriseListLazyImport
      parentRoute: typeof rootRoute
    }
    '/storybook': {
      preLoaderRoute: typeof StorybookLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CollectedCredsLazyRoute,
  DashboardLazyRoute,
  EntepriseLazyRoute,
  EntepriseListLazyRoute,
  StorybookLazyRoute,
])

/* prettier-ignore-end */
